FROM python:3.9-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/backend.py .

EXPOSE 5000

CMD ["python","-h","0.0.0.0", "-X" ,"backend.py"]